In [3]:
import torch
from torch.utils.data.dataset import Subset

# 仮想のデータセットを作成
# 例として、特徴量とラベルを持つテンソルを作成
features = torch.randn(100, 10)  # 100サンプル、10次元の特徴量
labels = torch.randint(0, 2, (100,))  # 0または1のラベル

# データセットを作成
dataset = list(zip(features, labels))

# Subsetを作成
indices = [0, 1, 2, 3]  # Subsetに含めるデータのインデックス
my_subset = Subset(dataset, indices)

# Subsetから特徴量とラベルを取り出す
subset_features, subset_labels = zip(*my_subset)
print(subset_features)

# 特徴量とラベルをテンソルに変換
subset_features = torch.stack(subset_features)
subset_labels = torch.tensor(subset_labels)

# 特徴量とラベルのテンソルを表示
print("Subset Features:", subset_features)
print("Subset Labels:", subset_labels)


(tensor([ 0.4804,  2.0605, -1.2786,  1.2366,  1.9014,  0.0617, -0.7193,  0.2368,
         0.5586, -0.2334]), tensor([-1.6933, -1.6290,  1.1134, -1.0186,  0.7134, -0.1536,  0.6368,  0.7000,
        -0.1847, -0.6507]), tensor([-0.2124,  1.3236, -1.8000, -0.1101, -0.2059,  0.3580, -0.4133,  0.6722,
        -0.6634, -0.1120]), tensor([ 1.0803, -1.5710, -0.0137, -0.5969,  0.8252,  0.4748,  0.4253,  0.8859,
         1.1500, -0.1496]))
Subset Features: tensor([[ 0.4804,  2.0605, -1.2786,  1.2366,  1.9014,  0.0617, -0.7193,  0.2368,
          0.5586, -0.2334],
        [-1.6933, -1.6290,  1.1134, -1.0186,  0.7134, -0.1536,  0.6368,  0.7000,
         -0.1847, -0.6507],
        [-0.2124,  1.3236, -1.8000, -0.1101, -0.2059,  0.3580, -0.4133,  0.6722,
         -0.6634, -0.1120],
        [ 1.0803, -1.5710, -0.0137, -0.5969,  0.8252,  0.4748,  0.4253,  0.8859,
          1.1500, -0.1496]])
Subset Labels: tensor([1, 0, 0, 1])


In [2]:
from torch.utils.data.dataset import Subset

# 仮想のデータセットを作成
# 例として、特徴量、ラベル、重みを持つテンソルを作成
features = torch.randn(100, 10)  # 100サンプル、10次元の特徴量
labels = torch.randint(0, 2, (100,))  # 0または1のラベル
weights = torch.rand(100)  # 重み

# データセットを作成
dataset = list(zip(features, labels, weights))

# Subsetを作成
indices = [0, 1, 2, 3]  # Subsetに含めるデータのインデックス
my_subset = Subset(dataset, indices)

# Subsetから特徴量とラベルを取り出す
# subset_features_labels = [(feat, label) for feat, label, _ in my_subset]

# 特徴量とラベルをテンソルに変換
subset_features, subset_labels = zip(*my_subset)
subset_features = torch.stack(subset_features)
subset_labels = torch.tensor(subset_labels)

# 特徴量とラベルのテンソルを表示
print("Subset Features:", subset_features)
print("Subset Labels:", subset_labels)


ValueError: too many values to unpack (expected 2)

In [1]:
import torch

# テンソル型が入ったリストを作成
tensor_list = [torch.randn(3, 3) for _ in range(5)]

# リストの内容を表示
for tensor in tensor_list:
    print(tensor)


tensor([[ 0.1541, -0.1982, -0.5346],
        [-1.2787, -1.1147,  1.4617],
        [-1.4033, -0.1882, -0.9098]])
tensor([[-1.0031, -0.7041, -0.3289],
        [-0.0409,  1.2207, -0.0297],
        [-0.9992, -0.9276,  1.2402]])
tensor([[ 1.8214, -0.3050, -2.2307],
        [-0.3143,  0.1313, -1.2995],
        [-1.2527,  1.9964,  0.8039]])
tensor([[-0.7993,  1.9684,  2.2722],
        [-0.4063, -0.3110, -0.1858],
        [-1.0147,  0.3165, -0.7351]])
tensor([[-0.6099, -1.3116,  0.1800],
        [ 0.0155, -0.0152,  0.0637],
        [ 1.4703,  0.1804, -1.3540]])
